#! /bin/bash

source "public.inc"

if [ "x$1" == "x" ]; then
	for t in `${ZKCTL_BIN} index-type list`; do 
		for p in `${ZKCTL_BIN} index-type list-index-partition --index-type-id=$t`; do
			${ZKCTL_BIN} index-partition list-index --index-partition-id=$p
		done
	done
else
	for t in `${ZKCTL_BIN} index-type list`; do 
		for p in `${ZKCTL_BIN} index-type list-index-partition --index-type-id=$t`; do
			${ZKCTL_BIN} index-partition list-index --index-partition-id=$p
		done
	done | grep $1
fi

